server.port: 8080

spring:
  application:
    name: cleverhause-api-gateway

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: 'http://localhost:8010/eureka'

# ROUTES

zuul:
  routes:
#    sensitiveHeaders: 'Cookie,Set-Cookie'
    users:
      sensitiveHeaders:
      path: '/api/users/**'
      url: 'http://localhost:8082/api/users'
    oauth:
      sensitiveHeaders:
      path: '/oauth/**'
      url: 'http://localhost:8081/oauth'
    oauth2:
      sensitiveHeaders:
      path: '/oauth2/authorization/**'
      url: 'http://localhost:8082/oauth2/authorization'
    login:
      sensitiveHeaders:
      path: '/login/**'
      url: 'http://localhost:8082/login'
    logout:
      sensitiveHeaders:
      path: '/logout/**'
      url: 'http://localhost:8082/logout'