server.port: 8083
spring:
 application.name: cleverhause-form-login-provider
 profiles: local, test

eureka:
 client:
  enabled: false

service-url.defaultZone: "${EUREKA_URI:http://localhost:8010/eureka}"


---

spring:
 profiles.active: local