spring.application.name: 'discovery-service'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

eureka.client.service-url:
  defaultZone: 'http://localhost:${server.port}/eureka'

server:
  port: 8010
