server.port: 8082
spring:
  application.name: cleverhause-users
  profiles.active: local
  datasource:
    name: local-users-db
    url: "jdbc:postgresql://localhost:5433/cleverhause_users_db"
    username: 'clever_admin'
    password: 'WindowsVista123'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
      hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
      hibernate.connection.characterEncoding: "UTF-8"
      hibernate.connection.charSet: "UTF-8"
      hibernate.temp.use_jdbc_metadata_defaults: "true"
      hibernate.physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  liquibase:
    enabled: false
  devtools:
    restart:
      enabled: true

eureka:
  client:
    enabled: false
    service-url.defaultZone: 'http://localhost:8010/eureka'