server.port: 0

spring:
  application.name: cleverhause-users
  profiles.active: local
  datasource:
    name: local-users-db
    url: "jdbc:postgresql://localhost:5433/cleverhause_users_db"
    username: 'clever_admin'
    password: 'WindowsVista123'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      - hibernate.dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
      - hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
      - hibernate.connection.characterEncoding: "UTF-8"
      - hibernate.connection.charSet: "UTF-8"
      - hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
  devtools:
    restart:
      enabled: true

logging.level.org.springframework.data: debug

eureka:
  client:
    enabled: false
    service-url.defaultZone: 'http://localhost:8010/eureka'