version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'postgres:11'
    restart: always
    networks:
      - app-tier
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - './init/database.sql:/docker-entrypoint-initdb.d/database.sql'
      - './init/insert.sql:/docker-entrypoint-initdb.d/insert.sql'
      - './data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  data:
    driver: local