spring:
  application.name: cleverhause-auth
  profiles.active: local
  datasource:
    name: local-docker-db
    url: "jdbc:postgresql://localhost:5432/cleverhause_db"
    username: 'clever_admin'
    password: 'WindowsVista123'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      - hibernate.dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
      - hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
      - hibernate.connection.characterEncoding: "UTF-8"
      - hibernate.connection.charSet: "UTF-8"
      - hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false

logging.level.org.springframework.data: debug