spring:
  devtools:
    restart:
      enabled: true
  security:
    oauth2:
      client:
        redirectUrl: "http://cleverhause.ru/oauth/token"
        registration:
          github:
            clientId: 'b4ccc96cfd49bff036a6'
            clientSecret: '178119e291c3b07a4684d1b31c35bb94b058329d'
            # need to do that if your redirect-uri differs from default one which is based on server port and host
            # (for local will be http://localhost:[server.port]/login/oauth2/code)
            redirect_uri: 'http://cleverhause.ru/login/oauth2/code/github'
            clientAuthenticationMethod: 'post'
          google:
            clientId: '400048896634-acal0divdad68tug694b4ifuhcdh71v9.apps.googleusercontent.com'
            clientSecret: 'qjKeuzeTaN2M9GWfDTYv1qLB'
security:
  oauth2:
    clients:
      clever-ui:
        clientId: 'client'
        secret: '{noop}secret'
        accessTokenLifeSecond: 3600
        refreshTokenLifeSecond: 50000
        grandTypes: 'password, client_credentials, refresh_token'
  #      'authorization_code, client_credentials, password, refresh_token'
        redirectUri:
        scopes: read