spring:
  devtools:
    restart:
      enabled: true

security:
  oauth2:
    clients:
      clever-ui:
        clientId: 'cleverhause-users'
        secret: 'secret'
        accessTokenLifeSecond: 3600
        refreshTokenLifeSecond: 50000
        grandTypes: 'authorization_code, refresh_token'
  #      'authorization_code, client_credentials, password, refresh_token'
        redirectUri:
        scopes: read
  authentication:
    providers:
      formLogin:
        providerClassName: "ru.cleverhause.auth.provider.FormLoginIdentityProvider"
        responseConverterClassName: "ru.cleverhause.auth.provider.FormLoginIdentityProvider"
